### ISSUE TITLE
Default Chain ID value in conditions

### ISSUE THREAD

**Issue by manumonti** [nucypher/nucypher-ts#114]
I found a little bit confusing the default values taken in the [Conditions](https://docs.threshold.network/app-development/threshold-access-control-tac/references/conditions) doc:

There is no reference to what network will be taken by default. If you inspect the code, the Göerli testnet will be taken. So I'm wondering myself:

Should we have a default value for this? Or should be mandatory to specify the chain ID when creating the Conditions object? What should be the default value in the former case, Ethereum mainnet or Göerli?

_Originally posted by @manumonti [and discussion] in https://github.com/nucypher/tdec/issues/86#issuecomment-1323621431_

**Comment by piotr-roslaniec** [comment]
I would favor removing the default value, I think it only adds confusion to the `Condition` usage. We should probably add some validation with a list (enum) of supported networks.

**Comment by theref** [comment]
I would be against adding some validation. That is done in `nucypher/nucypher` and the errors should bubble up. Adding more validation here means more things need to be kept in sync between the two repos

**Comment by piotr-roslaniec** [comment]
> Adding more validation here means more things need to be kept in sync between the two repos

We're already validating certain shared structures (such as `Condition`), and for a good reason - Since we're building a user-facing client I would prefer to fail early, especially since we don't enforce versioning on client-level https://github.com/nucypher/tdec/issues/66

**Comment by cygnusv** [comment]
> I would be against adding some validation. That is done in `nucypher/nucypher` and the errors should bubble up. Adding more validation here means more things need to be kept in sync between the two repos

But we should fail earlier, since conditions are associated to ciphertexts and it may be too late to change the condition later.

**Comment by KPrasch** [comment]
Agree.  It's more efficient and better UX to prevent the submission of invalid conditions.  However I think there is a little room for flexibility with regard to chain ID since we may not have a homogeneous deployment where all nodes are serving all supported chains.
