### ISSUE TITLE
[Gitbook docs] Lack of information in Get Started about WASM bindings

### ISSUE THREAD

**Issue by manumonti** [nucypher/nucypher-ts#119]
While I was trying to build a new app, I found a lack of information in [Get Started with TAC](https://docs.threshold.network/app-development/threshold-access-control-tac/get-started-with-tac). This caused that I got stuck in the [Step 2: Build a Cohort](https://docs.threshold.network/app-development/threshold-access-control-tac/get-started-with-tac#2.-build-a-cohort)

IMHO, the use of WASM bindings should be documented here as a kind of "prerequisite" or "step 0". The problem I found trying to build a basic app is:

1. `nucypher-ts` uses `nucypher-core` as a dependency. `nucypher-core` contains WASM bindings.
2. To run `nucypher-ts` (and hence, WASM from `nucypher-core`) we need a bundler that understands what WASM is.
3. Depending on what project we're running, two good options could be to use Webpack or Craco, but in any case, we need to tell them how to load WASM.

In any case, we have some examples of how to start building a new dApp [here](https://github.com/nucypher/tdec-nft-example), [here](https://github.com/nucypher/tdec-sandbox), and [here](https://github.com/nucypher/nucypher-ts/tree/main/examples), that could be linked in this documentation.

_Originally posted by @manumonti in https://github.com/nucypher/tdec/issues/86#issuecomment-1323426079_

**Comment by piotr-roslaniec** [comment]
Addressed in this [change set](https://app.gitbook.com/o/R2meumXNNad4y1B10iL7/s/WosjlL4zUGUMlcMfuSAp/~/changes/327Q86fbLjqEvWhacVOj/).
