### ISSUE TITLE
Redesign `Web3Provider`

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/nucypher-ts#130]
- `Web3Provider` is a wrapper for web3 providers
- It should provide a provider-agnostic way to `getAddress`, `sign`, and access other `provider` methods (such as transacting, etc.)
- Currently, it's only a thin wrapper for `ethers.providers.Web3Provider`
- Question:
  - Do we want to support providers other than `ethers`?   
  - Or do we want to remove this abstraction and rely on `ethers` completely? 
- Found an old version of this issue: https://github.com/nucypher/tdec/issues/65

**Comment by KPrasch** [comment]
Thanks for tracking this issue, which is essentially the reason why this PR was blocked.

https://github.com/nucypher/nucypher-ts-demo/pull/4

**Comment by piotr-roslaniec** [comment]
Closed by #139
