### ISSUE TITLE
Use "CommonJs" module for "require" exports

### ISSUE THREAD

**Issue by ghardin1314** [nucypher/nucypher-ts#153]
Not sure exactly the configuration yall are going for here, but we are having issues running this package server side on node.js. We would like it use it on the server to encrypt media for TAC.

Currently getting an `unexpected token "export"` error when installing `nucypher-ts`. I have gotten it to work before but it took some workarounds with `esm` modules, etc. Since you already have 2 build targets (`main`, `module`), would it be possible to convert the `main` to target `CommonJs`? 

https://github.com/nucypher/nucypher-ts/blob/3c4d2f6186bee3e036e9f8c4d6f713e0d94a9857/tsconfig.json#L9

**Comment by piotr-roslaniec** [comment]
Hi @ghardin1314, thanks for sharing that. We'd like support both CommonJs and ES modules. Tracking these changes here: https://github.com/nucypher/nucypher-ts/pull/154

**Comment by ghardin1314** [comment]
@piotr-roslaniec Any ideas on timelines for this? We would like to continue testing our process and this is a blocker for us

**Comment by piotr-roslaniec** [comment]
@ghardin1314 I just released these changes under `@nucypher/nucypher-ts@0.10.0-alpha.0`. Please let me know if it solves your issues. If not, I'd be happy to iterate over that.

**Comment by piotr-roslaniec** [comment]
Closed by #154
