### ISSUE TITLE
Does Enrico bear a secret in order to demonstrate his standing to adhere conditions?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-ts#155]
In a scenario where Enrico has standing to use a Strategy funded by a particular Alice, does he have a secret (eg, decrypting material to receive an authorization token, or signing material fit to participate in a derivation scheme) requiring local custody?

This perhaps turns, in full or in part, by the matter of how, in the scope of the protocol, Alice authorizes this adherence: 

https://github.com/nucypher/nucypher/issues/3050

**Comment by jMyles** [comment]
Notice, this is separate from the secret material that Enrico might use to, for example, create a signature in the process of actually adhering the conditions.  That part is here:

https://github.com/nucypher/nucypher-ts/issues/157

**Comment by derekpierre** [comment]
Is this issue resolved by use of the `g_inv` parameter by ferveo? (cc @piotr-roslaniec , @KPrasch )

**Comment by cygnusv** [comment]
No, the g_inv parameter is a public parameter of the elliptic curve we use (BLS12-381)

**Comment by derekpierre** [comment]
Is this resolved by the Allow List work done on the contract side, and which will be completed in `nucypher` via https://github.com/nucypher/nucypher/pull/3213?

**Comment by cygnusv** [comment]
Closed by https://github.com/nucypher/nucypher-contracts/pull/89

**Comment by jMyles** [comment]
I broadly agree that the AllowLogic design (ie, https://github.com/nucypher/nucypher-contracts/pull/89) represents a disposition to this issue.

Though I do want to note: different AllowLogic schemes may present different secret custody requirements, and also cause dramatically increased value for the Enrico secret in question.  I hope we stay mindful of this.
