### ISSUE TITLE
Update `nucypher-core` to `0.6.x`

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/nucypher-ts#158]
- Note that `0.6.0` introduced [breaking changes](https://github.com/nucypher/nucypher-core/blob/main/CHANGELOG.md)
- We need make sure that `nucypher-ts` will be compatible with testnets after merging this change

**Comment by derekpierre** [comment]
@piotr-roslaniec I assume that this is really going to be an update to `nucypher-core` v0.6.x since this is what `nucypher` is currently working over?

**Comment by piotr-roslaniec** [comment]
@derekpierre Yes, at the time `nucypher@0.5.x` was the newest release. I'm going to update this issue.

**Comment by piotr-roslaniec** [comment]
Closed by #193
