### ISSUE TITLE
Does Ursula encrypt the CFrag for SpecificManBob?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-ts#164]
Will Bob, along with his request, ask Ursula to encrypt the CFrag for him?

If so, we'll need to custody a decryption secret for him.

**Comment by piotr-roslaniec** [comment]
What do we mean by `CFrag` here? Are we referring to PRE here?

If we're referring to tdec, this should be solved by https://github.com/nucypher/nucypher-ts/pull/219

CC @jMyles

**Comment by jMyles** [comment]
Agreed; this is closed by #219.
