### ISSUE TITLE
Does SpecificManBob have the ability to demonstrate his TransactingPower for the purposes of fulfilling a Condition?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher-ts#165]
In a scenario where a Condition requires some interactivity (eg, "Bob must have NFT 0x1234, and then supply a signature of <this payload> along with the most recent block hash), then Bob will need to have a transacting secret.  

This issue is most likely wontfix, except in a scenario where we need to separately custody the secret from his wallet.

**Comment by jMyles** [comment]
We also consider the role, in this structure, of Event emission: https://github.com/nucypher/tdec/issues/61

**Comment by piotr-roslaniec** [comment]
AFAIK this was fixed by introducing message signing to condition context: https://github.com/nucypher/nucypher-ts/blob/59b9c8cab2802b81672860e87254b13ea9e810df/src/policies/conditions.ts#L390

CC @jMyles

**Comment by jMyles** [comment]
Presuming the design decision is to always use the secret of the transacting power (ie, Bob's wallet and no other pair), then I agree that this is closed.
