### ISSUE TITLE
Some questions regarding `nucypher-ts` API/SDK

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher-ts#171]
I did a very cursory review of the `nucypher-ts` code base and had some questions regarding the design of the API. Please excuse my ignorance and bear with me regarding any misconceptions about ts/js common practices:

1. Any reason `Operator.OR` and `Operator.AND` can't be static singletons?
2. How come supported chains ids declared in Condition base class?
3. How come `EvmCondition` doesn't extend `RPCCondition`?
4. Is `function_abi` supported in nucypher-ts? Related to nucypher/tdec#99 
     * EvmCondition doesn't seem that general, but rather specific methods? Related to `function_abi` support?
5. Does `getContextParameters` check for context variables in key - which is currently supported in the python-side (although I have questions about that - see https://github.com/nucypher/nucypher/issues/3027#issuecomment-1325209266
6. `createWalletSignature`, should probably use `cbd` instead of `tdec` for the `name` property in `domain` for the EIP signature data.

**Comment by piotr-roslaniec** [comment]
Closed by #201
