### ISSUE TITLE
Support `ThresholdDecryption*` primitives for Ferveo-backed DKG

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/nucypher-ts#189]
- `ThresholdDecryptionRequest`, `ThresholdDecryptionResponse`
@KPrasch

**Comment by derekpierre** [comment]
Related to https://github.com/nucypher/nucypher/issues/3081

This could be done in 2 phases; kind of what I did for Porter:
- Non-encrypted version (could be started now)
- E2EE version (requires related PRs in https://github.com/nucypher/nucypher/issues/3081 to be completed first)

Something to think about.

**Comment by piotr-roslaniec** [comment]
@derekpierre I will start working on phase one, i.e. integrating with Porter's `/decrypt`.

**Comment by derekpierre** [comment]
> @derekpierre I will start working on phase one, i.e. integrating with Porter's `/decrypt`.

👍. You can look at https://github.com/nucypher/nucypher-porter/pull/24 for what the final E2EE Porter side of things will look like. It is pretty much completed but probably needs some clean up.

**Comment by piotr-roslaniec** [comment]
Closed by #210
