### ISSUE TITLE
Update v7.0 demos/examples

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher-ts#194]
Potential features: 
- Dashboard for monitoring/flagging Ursula status (particularly useful for Permissionless cohort users) 

Note: dependent on bindings etc

**Comment by piotr-roslaniec** [comment]
Do we know what is the scope of this demo?

For `nucypher-ts` we have the following demos:
- https://github.com/nucypher/alpha-leaks-demo
- https://github.com/nucypher/nucypher-ts-demo
- https://github.com/nucypher/nucypher-ts-demo-tdec
- https://github.com/nucypher/tdec-sandbox
- https://github.com/nucypher/tdec-nft-example

We're considering moving demos to `nucypher-ts` repository under `./demos` directory.

We also (are going to) have the following integration examples:
- https://github.com/piotr-roslaniec/nucypher-ts/tree/refactor-packages/examples (awaiting #301 merge)
