### ISSUE TITLE
Refactor `EvmCondition` as a subclass of `RpcCondition`

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/nucypher-ts#206]
- Originally described [in this issue](https://github.com/nucypher/nucypher-ts/issues/171#issuecomment-1432436214)
- Maybe instead of subclassing we just extend the `RpcCondition.schema` ? 
- RFC

**Comment by derekpierre** [comment]
Also, based on #218 (from https://github.com/nucypher/nucypher/pull/3139), you could think about TimeCondition extending RpcCondition or the RpcCondition.schema.
