### ISSUE TITLE
[Docs] Revisiting WASM integration in nucypher-ts

### ISSUE THREAD

**Issue by manumonti** [nucypher/nucypher-ts#256]
From an **adopter with no previous experience** perspective, I think the WASM configuration can be tricky.

Reading the [Get started - Install nucypher-ts section](https://docs.threshold.network/app-development/threshold-access-control-tac/get-started-with-tac#1.-install-nucypher-ts), we can extract that:

First, we can read "_One dependency takes advantage of WASM_". Does this mean it is totally necessary to handle WASM? or is there a chance that I finally use some nucypher-ts component that doesn't need to use WASM? If it's mandatory to integrate WASM, I would say something like "nucypher-ts takes advantage of WASM", treating the package as a whole.

Also, we find three links here: 
1. One explaining [what WASM is](https://developer.mozilla.org/en-US/docs/WebAssembly). This is ok, but I would prefer a one-line description instead of a link with more information and subsections that a developer doesn't need to know to just use nucypher-ts.
2. Another explaining the different ways in which [I can load and run WASM](https://developer.mozilla.org/en-US/docs/WebAssembly/Loading_and_running) code, using `Fetch`, `WebAssembly.intantiate`, `XMLHttpRequest` and so on. AFAIK, a developer importing nucypher-ts doesn't need to do this, so this information can be confusing and unnecessary.
3. Another link with a webpack template (wasm-pack)[https://rustwasm.github.io/docs/wasm-pack/tutorials/npm-browser-packages/using-your-library.html] where WASM code is loaded. IMHO this is a not very useful read since it is not very oriented to nucypher-ts, and it would be better if a link to some simple nucypher-ts example is given here (like [webpack-bundler](https://github.com/nucypher/nucypher-ts/tree/main/examples/webpack-bundler)). Also, as mentioned in #255, this code is outdated.
  
As a suggestion, maybe we need a new section for WASM configuration. Do you think this would make easy the understanding of WASM implications?

These are my impressions when trying to put myself in nucypher-newbie shoes. But these can be partial or I  may be missing information, so we can discuss this here.

**Comment by piotr-roslaniec** [comment]
I agree with your remarks on 1 & 2 - These could be replaced by a link to external resource with some explanation and a quick "Getting started" section. `nucypher-ts` users should only need enough context about WASM to be able to run `nucypher-ts` in their preferred environment (web, mobile, node).

I think there is a prerequisite to a satisfactory documentation on WASM - The "developer" experience of bundling / packaging of `nucyper-ts`. This issue has already been documented here: https://github.com/nucypher/nucypher-ts/issues/120. Solving this would make the link described in point 3 redundant.

**Comment by piotr-roslaniec** [comment]
Closed by #299
