### ISSUE TITLE
[Docs] About integrating of nucypher-ts in a existing no-WASM project

### ISSUE THREAD

**Issue by manumonti** [nucypher/nucypher-ts#257]
Trying to put on a new adopter hat, I would say that nucypher-ts have [several examples](https://github.com/nucypher/nucypher-ts/tree/main/examples) about how to create a new project that includes a bundler already configured for nucypher WASM, but I don't find too much information about how to integrate nucypher-ts (especially, the WASM part) in an existing project.

IMHO (and I have to admit that I don't have a great experience as web dev.), these examples would not be enough to use nucypher-ts in a project already built which uses a tech stack with some library like react or some frameworks like Next.js that include its own configurations.

But honestly, I'm not sure how we can make this easier. Better documentation? Some change from the code perspective?

**Comment by piotr-roslaniec** [comment]
Are we talking about a case where there is no bundler set up in an existing project (but it's okay to add it) or about a project that will not use a bundler? The latter refers to case reported by one of our users, where they wanted to use `nucypher-ts` in a CDN distribution.

In the case of former we could provide a step-by-step integration guide based on the existing examples. So we could have (for example) a "Getting started with `nucypher-ts` and React" guide where we use `create-react-app` to set up `nucypher-ts` in a new project from scratch. How does that help? Well, there is a number of steps in this guide that users could refer to at any point of setting up their project, either a new or existing one.

**Comment by manumonti** [comment]
> Are we talking about a case where there is no bundler set up in an existing project (but it's okay to add it) or about a project that will not use a bundler?

I think it is worth discussing both cases.

**Comment by piotr-roslaniec** [comment]
Closed by #299
