### ISSUE TITLE
Error on creating policy

### ISSUE THREAD

**Issue by kashishkhullar** [nucypher/nucypher-ts#57]
### Description
Getting the following error in the console when clicking "Go" to create policy in `react-craco` example:

_`Uncaught (in promise) Error: No contracts found for chainId: 1`_

### Screenshot
Here is a screenshot for the same:

![image](https://user-images.githubusercontent.com/22838528/178941595-b690fb4a-6594-4af5-998c-db7ddb1f4aba.png)

**Comment by piotr-roslaniec** [comment]
Hi @kashishkhullar. 
Chain ID 1 corresponds to the Ethereum mainnet. Currently, `nucypher-ts` [supports Polygon and Mumbai networks only](https://github.com/nucypher/nucypher-ts#supported-networks).
