### ISSUE TITLE
Add `ConditionContext` to `PostRetrieveCFragsRequest`

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/nucypher-ts#79]
- Use `context` to store certain parameters from `ConditionSet` that require user interaction. 
- `ConditonContext` is a key-value map, `Record<string, string|number>`
- Related issue: #77 
- Related PR: https://github.com/nucypher/nucypher-ts/pull/77/files#r952763415

**Comment by derekpierre** [comment]
Related to https://github.com/nucypher/tdec/issues/39.
