### ISSUE TITLE
Since its a ts project, consider using Zod instead of joi?

### ISSUE THREAD

**Issue by ShravanSunder** [nucypher/nucypher-ts#94]
I noticed that you're using joi in condition assertions.  Its much more fully developed ground up for typescript.  @piotr-roslaniec

**Comment by piotr-roslaniec** [comment]
Hi @ShravanSunder, thanks for sharing, I will look into that.

**Comment by ShravanSunder** [comment]
here's the docs:  https://zod.dev/
https://github.com/colinhacks/zod

**Comment by derekpierre** [comment]
Closed via https://github.com/nucypher/nucypher-ts/pull/267.
